project_id = "rlodbxuxntqmttwfrnik"

[functions.generate-website]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false
